#!/bin/bash

# Home Directory Cleaner 2012.6.12
# Copyright (c) 2012 Renato Silva
# GNU GPLv2 licensed

# For running this on sudo and gksu do the following:
# sudo() { command sudo "$@"; command sudo homeclean --root; }
# gksu() { command gksu "$@"; command sudo homeclean --root; }

case "$1" in
    "--help") echo "Usage: $0 [--root]" && exit;;
    "--root") home=~root;;
           *) home=~
esac

files=(
    ".*.log"
    ".xsession-errors*"
    ".thumbnails"
)

for file in "${files[@]}"; do
    rm -rfv "$home"/$file
done
